version: '3'
services:
  api_call:
    build: 
      context: ./api_call
    env_file:
      - .env
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
    build:
      context: ./kafka_server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server/kafka_init.sh:/kafka_init.sh
    command: ["/bin/sh", "-c", "/kafka_init.sh && start-kafka.sh"]
  # 여기에 api_call, front 등 다른 서비스들을 추가