version: '3'
services:
  api_service:
    container_name: api_news
    build: 
      context: ./api_call
    env_file:
      - .env
    networks:
      - mynetwork

  zookeeper_service:
    image: ghcr.io/arm64-compat/confluentinc/cp-zookeeper:7.1.1 # m1용 이미지
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka_service:
    container_name: kafka_service
    build:
      context: ./kafka_server
    depends_on:
      - zookeeper_service
    ports:
      - "9092:9092"
    expose:
      - '29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_service:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
    networks:
      - mynetwork

  consumer_service:
      container_name: kafka_consumer
      build:
        context: ./kafka_consumer  # Kafka Consumer 코드가 있는 디렉토리
      depends_on:
        - kafka_service
      networks:
        - mynetwork
      env_file:
        - .env
      # 환경 변수 및 볼륨 설정(필요한 경우)

  mongodb_service:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    
networks:
  mynetwork: {}
